### ISSUE TITLE
Most recent version compose-mode (0.5.4) not available from pypi

### ISSUE THREAD

**Issue by tannart** [KitB/compose-mode#6]
Hi there

I submitted a fix for this 8 months ago but the version has not been pushed up to pypi, can you push it up so I can install it through a requirements file?
Cheers

Regards
Charlie

**Comment by tannart** [comment]
Alternatively if you aren't interested in maintaining it any more I'd be happy to take it over from you.

**Comment by KitB** [comment]
I'd be happy for you to take it over. What's your pypi account so I can transfer it over?

**Comment by tannart** [comment]
My username is cmacb and my email is charliembrodie@gmail.com, I'm not sure what's required for an ownership transfer though so let me know if you need anything else.

Thanks for this by the way!

**Comment by KitB** [comment]
Done, thanks for being willing to take over.
